/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adlawan;

import config.dbConnector;
import internalPages.customerPage;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author BOSS
 */
public class customerForm extends javax.swing.JFrame {

    /**
     * Creates new form customerForm
     */
    public customerForm() {
        initComponents();
    }
    
    public void close(){
    this.dispose();
        dashBoard dash = new dashBoard();
        dash.setVisible(true);
        customerPage up = new customerPage();
        dash.maindesktop.add(up).setVisible(true);
    }
    
    Color navcolor = new Color (255,204,255);
    Color headcolor = new Color (204,51,255);
    Color bodycolor = new Color (153,153,255);
    
    public String gender;
    public String action;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        c_label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        c_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        c_fname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        c_lname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        c_status = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        c_address = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        c_contact = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        c_email = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CUSTOMER FORM");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 230, 60);

        close.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setText("X");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel2.add(close);
        close.setBounds(710, 10, 60, 40);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 770, 60));

        jPanel3.setBackground(new java.awt.Color(255, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        c_label.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        c_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c_label.setText("LABEL");
        jPanel3.add(c_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 100, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, -1, 40));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Customer ID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 140, 30));

        c_id.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        c_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        c_id.setEnabled(false);
        c_id.setOpaque(false);
        jPanel1.add(c_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 210, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("First Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 140, 30));

        c_fname.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        c_fname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c_fname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        c_fname.setOpaque(false);
        jPanel1.add(c_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 210, 30));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Last Name:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 140, 30));

        c_lname.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        c_lname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c_lname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        c_lname.setOpaque(false);
        jPanel1.add(c_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 210, 30));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Gender:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 140, 30));

        male.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        male.setText("MALE");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 70, -1));

        female.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        female.setText("FEMALE");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 80, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Status:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 140, 30));

        c_status.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        c_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married", " " }));
        jPanel1.add(c_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 210, 30));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Address:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 110, 30));

        c_address.setColumns(20);
        c_address.setRows(5);
        jScrollPane2.setViewportView(c_address);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 210, 110));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Contact:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 110, 30));

        c_contact.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        c_contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c_contact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        c_contact.setOpaque(false);
        jPanel1.add(c_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 210, 30));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Email:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 110, 30));

        c_email.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        c_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c_email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        c_email.setOpaque(false);
        jPanel1.add(c_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 210, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        jPanel3.setBackground(bodycolor);
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        jPanel3.setBackground(navcolor);
    }//GEN-LAST:event_jPanel3MouseExited

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        female.setSelected(false);
        if(male.isSelected()){
            gender = "Male";
        }else{
            gender = null;
        }
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        male.setSelected(false);
        if(female.isSelected()){
            gender = "Female";
        }else{
            gender = null;
        }
    }//GEN-LAST:event_femaleActionPerformed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        close();
    }//GEN-LAST:event_closeMouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        if(action.equals("Add")){
            dbConnector dbc = new dbConnector();
            int result = dbc.insertData("INSERT INTO tbl_customer(c_fname,c_lname,c_gender,c_status,c_address,c_contact,c_email)"
                    + "VALUES('"+c_fname.getText()+"','"+c_lname.getText()+"','"+gender+"','"+c_status.getSelectedItem()+"','"+c_address.getText()+"','"+c_contact.getText()+"','"+c_email.getText()+"')");
            if(result == 1){
                JOptionPane.showMessageDialog(null,"Succesfully Save!");
                close();
            }else{
                System.out.println("Saving Data Failed");       
            }
        }else if (action.equals("UPDATE")){
        dbConnector dbc = new dbConnector();
        dbc.updateData("UPDATE tbl_customer SET c_fname = '"+c_fname.getText()+"',c_lname ='"+c_lname.getText()+"',"
                + "c_gender ='"+gender+"',c_status = '"+c_status.getSelectedItem()+"',c_address = '"+c_address.getText()+"',"
                        + "c_contact = '"+c_contact.getText()+"',c_email = '"+c_email.getText()+"'" 
                                + "WHERE c_id ='"+c_id.getText()+"'" );
        close();
        }else{
            JOptionPane.showMessageDialog(null,"No Action Selected!");
            close();
        }
    }//GEN-LAST:event_jPanel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea c_address;
    public javax.swing.JTextField c_contact;
    public javax.swing.JTextField c_email;
    public javax.swing.JTextField c_fname;
    public javax.swing.JTextField c_id;
    public javax.swing.JLabel c_label;
    public javax.swing.JTextField c_lname;
    public javax.swing.JComboBox<String> c_status;
    private javax.swing.JLabel close;
    public javax.swing.JRadioButton female;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JRadioButton male;
    // End of variables declaration//GEN-END:variables
}
